//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramInformationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChairInfo
    {
        public int ChairID { get; set; }
        public string DepartmentAbbrev { get; set; }
        public string ChairFirstName { get; set; }
        public string ChairLastName { get; set; }
        public bool Acting { get; set; }
        public Nullable<System.DateTime> ChairStartDate { get; set; }
        public Nullable<System.DateTime> ChairEndDate { get; set; }
        public string ChairDescription { get; set; }
    
        public virtual DepartmentInfo DepartmentInfo { get; set; }
    }
}
