//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramInformationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordinatorInfo
    {
        public int CoordinatorID { get; set; }
        public string ProgramCode { get; set; }
        public string CoordinatorFirstName { get; set; }
        public string CoordinatorLastName { get; set; }
        public bool Acting { get; set; }
        public Nullable<System.DateTime> CoordinatorStartDate { get; set; }
        public Nullable<System.DateTime> CoordinatorEndDate { get; set; }
        public string CoordinatorDescription { get; set; }
    
        public virtual ProgramInfo ProgramInfo { get; set; }
    }
}
