//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramInformationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVSApproval
    {
        public int CVSID { get; set; }
        public string ProgramAbbrev { get; set; }
        public string CVSApplication { get; set; }
        public string ModelRoute { get; set; }
        public bool CVSValidation { get; set; }
        public System.DateTime ResponseDate { get; set; }
        public string ValidationLetter { get; set; }
    
        public virtual ProgramInfo ProgramInfo { get; set; }
    }
}
