//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramInformationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeanInfo
    {
        public int DeanID { get; set; }
        public string SchoolAbbrev { get; set; }
        public string DeanFirstName { get; set; }
        public string DeanLastName { get; set; }
        public Nullable<System.DateTime> DeanStartDate { get; set; }
        public System.DateTime DeanEndDate { get; set; }
        public Nullable<bool> Acting { get; set; }
        public string DeanDescription { get; set; }
    
        public virtual SchoolInfo SchoolInfo { get; set; }
    }
}
