//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramInformationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepartmentInfo()
        {
            this.ChairInfoes = new HashSet<ChairInfo>();
            this.ProgramInfoes = new HashSet<ProgramInfo>();
        }
    
        public string DepartmentAbbrev { get; set; }
        public string SchoolAbbrev { get; set; }
        public string DepartmentName { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChairInfo> ChairInfoes { get; set; }
        public virtual SchoolInfo SchoolInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramInfo> ProgramInfoes { get; set; }
    }
}
