//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramInformationApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgramInfoEntities : DbContext
    {
        public ProgramInfoEntities()
            : base("name=ProgramInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ChairInfo> ChairInfoes { get; set; }
        public virtual DbSet<CoordinatorInfo> CoordinatorInfoes { get; set; }
        public virtual DbSet<DeanInfo> DeanInfoes { get; set; }
        public virtual DbSet<DepartmentInfo> DepartmentInfoes { get; set; }
        public virtual DbSet<ProgramInfo> ProgramInfoes { get; set; }
        public virtual DbSet<SchoolInfo> SchoolInfoes { get; set; }
        public virtual DbSet<CVSApproval> CVSApprovals { get; set; }
        public virtual DbSet<MTCUApproval> MTCUApprovals { get; set; }
        public virtual DbSet<PEQABReport> PEQABReports { get; set; }
    }
}
