//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramInformationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTCUApproval
    {
        public int MTCUID { get; set; }
        public string ProgramAbbrev { get; set; }
        public string MTCURequest { get; set; }
        public bool MTCUDecision { get; set; }
        public System.DateTime ResponseDate { get; set; }
        public string ApprovalLetter { get; set; }
        public string FundingCode { get; set; }
        public string FundingName { get; set; }
        public string APSCode { get; set; }
        public string APSName { get; set; }
    
        public virtual ProgramInfo ProgramInfo { get; set; }
    }
}
