//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramInformationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEQABReport
    {
        public int PEQABID { get; set; }
        public string ProgramAbbrev { get; set; }
        public string PEQABApprovalReprot { get; set; }
        public string PEAQBDesicion { get; set; }
        public System.DateTime ResponseDate { get; set; }
    
        public virtual ProgramInfo ProgramInfo { get; set; }
    }
}
