//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramInformationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramInfo()
        {
            this.CoordinatorInfoes = new HashSet<CoordinatorInfo>();
            this.CVSApprovals = new HashSet<CVSApproval>();
            this.MTCUApprovals = new HashSet<MTCUApproval>();
            this.PEQABReports = new HashSet<PEQABReport>();
        }
    
        public string ProgramCode { get; set; }
        public string DepartmentAbbrev { get; set; }
        public string ProgramName { get; set; }
        public string Credential { get; set; }
        public int ProgramDuration { get; set; }
        public System.DateTime StartDate { get; set; }
        public string ProgramStatus { get; set; }
        public string Reason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordinatorInfo> CoordinatorInfoes { get; set; }
        public virtual DepartmentInfo DepartmentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVSApproval> CVSApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTCUApproval> MTCUApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEQABReport> PEQABReports { get; set; }
    }
}
